Remove connect-mongo
The old version gave errors during initialization, and upon reading the docs it does not appear that the session functionality is really used.

```
{ Error: Cannot find module '../build/Release/bson'
```